DROP TABLE IF EXISTS authors;
CREATE TABLE authors (
    id BIGSERIAL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255)
);

DROP TABLE IF EXISTS genres;
CREATE TABLE genres (
    id BIGSERIAL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255)
);

DROP TABLE IF EXISTS books;
CREATE TABLE books(
    id BIGSERIAL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255)
);
